### ISSUE TITLE
Upgrade GOV.UK Frontend to 5.4.0

### ISSUE THREAD

**Issue by markhobson** [LandRegistry/govuk-frontend-jinja#77]
[GOV.UK Frontend](https://github.com/alphagov/govuk-frontend) should be upgraded from 5.1.0 to 5.4.0.

**Comment by tim-s-ccs** [comment]
I've had a look at doing this in my fork of this repo https://github.com/tim-s-ccs/govuk-frontend-jinja/pull/7

If my changes regarding testing are accepted then this can obviously be use to help speed things along

**Comment by matthew-shaw** [comment]
Updated in #78 👍🏻
